server:
  port: 1111
  error:
    include-message: always
    include-binding-errors: always

#Configuracion de base de datos
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_matricula
    username: postgres
    password: root
  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"     

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}